#ifndef DEF_HEADSERVO
#define DEF_HEADSERVO

/*!
 * \file HeadServo.h
 * \brief HeadServo structure's
 * \author MORANT Thbiaut
 */

#include <Servo.h>
#include "Arduino.h"


class HeadServo {
	public:
		/*!
		 *  \brief Constructor
		 *
		 *  Constructor of the HeadServo Class'
		 *
		 *  \param new_position : pin to control the servo motor
		 */
		HeadServo(int new_ServoMotor_Pin);

		/*!
		 *  \brief Destructor
		 *
		 *  Destructor of the HeadServo Class'
		 */
		~HeadServo();


		/*!
		 *  \brief change the position of the servo motor
		 *
		 *  this distance is generated by the InfraRed sensor
		 *
		 *  \param new_position :new position
		 */
		void setPosition(int new_position);

		/*!
		 *  \brief return the position of the servo motor
		 *
		 *  \return the position
		 */
		int getPosition();

	private:
		Servo servo;/*!< object used to control servo motor*/
		int servoMap;/*!< pin to control the servo motor*/

};

#endif