#ifndef DEF_INFRAREDSENSOR
#define DEF_INFRAREDSENSOR

/*!
 * \file InfraRedSensor.h
 * \brief InfraRedSensor structure's
 * \author MORANT Thbiaut
 */

#include "Arduino.h"


class InfraRedSensor {
	public:
		/*!
		 *  \brief Constructor
		 *
		 *  Constructor of the InfraRedSensor Class'
		 *
		 *  \param init_sensor_Pin : pin to receive information from the sensor
		 */
		InfraRedSensor(int init_sensor_Pin);

		/*!
		 *  \brief Destructor
		 *
		 *  Destructor of the InfraRedSensor Class'
		 */
		~InfraRedSensor();


		/*!
		 *  \brief return the distance between an object and the robot
		 *
		 *  this distance is generated by the InfraRed sensor
		 *
		 *  \return the distance
		 */
		float getDistance();

	private:
		int sensor_Pin;/*!< pin for the reception of information*/
		
};

#endif