#ifndef DEF_SENSOR
#define DEF_SENSOR

/*!
 * \file Sensor.h
 * \brief Sensor structure's
 * \author MORANT Thbiaut
 */

#include "Arduino.h"

#include "./Ultrason.h"
#include "./InfraRedSensor.h"


class Sensor {
	public:
		/*!
		 *  \brief Constructor
		 *
		 *  Constructor of the Sensor Class'
		 *
		 *  \param init_InfraRedSensor_Pin : pin of the InfraRedSeonsor
		 *  \param init_echo_Pin : pin for the reception of information of the Ultrason Sensor
		 *  \param init_trigger_Pin : pin for the emition of information of the Ultrason Sensor
		 */
		Sensor(int init_InfraRedSensor_Pin, int init_echo_Pin, int init_trigger_Pin);

		/*!
		 *  \brief Destructor
		 *
		 *  Destructor of the Sensor Class'
		 */
		~Sensor();


		/*!
		 *  \brief return the distance between an object and the robot
		 *
		 *  this distance is generated by the ultrason
		 *
		 *  \return the distance
		 */
		float getDistanceUltrasion();
		/*!
		 *  \brief return the distance between an object and the robot
		 *
		 *  this distance is generated by the InfraRed sensor
		 *
		 *  \return the distance
		 */
		float getDistanceInfraRedSensor();

	private:
		InfraRedSensor *infraRedSensor;/*!< object used to control the infraRed Sensor*/
		Ultrason *ultrason;/*!< object used to control the ultrason Sensor*/
		
};

#endif